package com.cybershield.app.model

data class ScreenSpec(val title: String, val route: String, val group: String, val kind: String)

object ScreenRegistry {
    val all: List<ScreenSpec> = listOf(
        ScreenSpec("01 Splash \u2014 Security Initialization", "01-splash-security-initialization", "Core Product Flow", "splash"),
        ScreenSpec("02 Login \u2014 Real Credentials", "02-login-real-credentials", "Core Product Flow", "login"),
        ScreenSpec("03 Register \u2014 Full Credentials", "03-register-full-credentials", "Core Product Flow", "register"),
        ScreenSpec("04 Forgot Password", "04-forgot-password", "Core Product Flow", "forgot"),
        ScreenSpec("05 Home \u2014 Phone Manager", "05-home-phone-manager", "Core Product Flow", "home"),
        ScreenSpec("06 Device Health", "06-device-health", "Core Product Flow", "device"),
        ScreenSpec("07 Apps Manager", "07-apps-manager", "Core Product Flow", "apps"),
        ScreenSpec("08 Privacy Center", "08-privacy-center", "Core Product Flow", "privacy"),
        ScreenSpec("09 Storage Manager", "09-storage-manager", "Core Product Flow", "storage"),
        ScreenSpec("10 Network Guard", "10-network-guard", "Core Product Flow", "network"),
        ScreenSpec("11 Scan Center", "11-scan-center", "Core Product Flow", "scan"),
        ScreenSpec("12 Message Scam Result", "12-message-scam-result", "Core Product Flow", "message_result"),
        ScreenSpec("13 URL Protection", "13-url-protection", "Core Product Flow", "url_protection"),
        ScreenSpec("14 QR & Payment Safety", "14-qr-and-payment-safety", "Core Product Flow", "qr_payment"),
        ScreenSpec("15 AI Security Assistant", "15-ai-security-assistant", "Core Product Flow", "ai"),
        ScreenSpec("16 Alert Center", "16-alert-center", "Core Product Flow", "alerts"),
        ScreenSpec("17 Personal Cyber-Risk", "17-personal-cyber-risk", "Core Product Flow", "risk"),
        ScreenSpec("18 Family Protection", "18-family-protection", "Core Product Flow", "family"),
        ScreenSpec("19 Scan History & Evidence", "19-scan-history-and-evidence", "Core Product Flow", "history"),
        ScreenSpec("20 Settings & Security", "20-settings-and-security", "Core Product Flow", "settings"),
        ScreenSpec("Settings Detail 01 \u2022 Account", "settings-detail-01-account", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 02 \u2022 Protection", "settings-detail-02-protection", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 03 \u2022 Notifications", "settings-detail-03-notifications", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 04 \u2022 Privacy", "settings-detail-04-privacy", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 05 \u2022 AI", "settings-detail-05-ai", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 06 \u2022 Trusted Devices", "settings-detail-06-trusted-devices", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 07 \u2022 Data & Storage", "settings-detail-07-data-and-storage", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 08 \u2022 Language", "settings-detail-08-language", "Settings", "settings_detail"),
        ScreenSpec("Settings Detail 09 \u2022 Security Logs", "settings-detail-09-security-logs", "Settings", "settings_detail"),
        ScreenSpec("Overall Security Score", "01-security-center-overall-security-score", "01 Security Center", "feature"),
        ScreenSpec("Device Security Status", "01-security-center-device-security-status", "01 Security Center", "feature"),
        ScreenSpec("Threat Status", "01-security-center-threat-status", "01 Security Center", "feature"),
        ScreenSpec("Privacy Status", "01-security-center-privacy-status", "01 Security Center", "feature"),
        ScreenSpec("Network Status", "01-security-center-network-status", "01 Security Center", "feature"),
        ScreenSpec("Account Security", "01-security-center-account-security", "01 Security Center", "feature"),
        ScreenSpec("Security Recommendations", "01-security-center-security-recommendations", "01 Security Center", "feature"),
        ScreenSpec("Last Security Scan", "01-security-center-last-security-scan", "01 Security Center", "feature"),
        ScreenSpec("Device Information", "02-device-protection-device-information", "02 Device Protection", "feature"),
        ScreenSpec("OS Security", "02-device-protection-os-security", "02 Device Protection", "feature"),
        ScreenSpec("Security Updates", "02-device-protection-security-updates", "02 Device Protection", "feature"),
        ScreenSpec("Device Configuration", "02-device-protection-device-configuration", "02 Device Protection", "feature"),
        ScreenSpec("Screen Lock Status", "02-device-protection-screen-lock-status", "02 Device Protection", "feature"),
        ScreenSpec("Encryption Status", "02-device-protection-encryption-status", "02 Device Protection", "feature"),
        ScreenSpec("Developer Options Status", "02-device-protection-developer-options-status", "02 Device Protection", "feature"),
        ScreenSpec("Root/Jailbreak Detection", "02-device-protection-root-jailbreak-detection", "02 Device Protection", "feature"),
        ScreenSpec("Device Integrity", "02-device-protection-device-integrity", "02 Device Protection", "feature"),
        ScreenSpec("Installed Applications", "03-app-security-installed-applications", "03 App Security", "feature"),
        ScreenSpec("Dangerous Apps", "03-app-security-dangerous-apps", "03 App Security", "feature"),
        ScreenSpec("Suspicious Apps", "03-app-security-suspicious-apps", "03 App Security", "feature"),
        ScreenSpec("App Risk Score", "03-app-security-app-risk-score", "03 App Security", "feature"),
        ScreenSpec("App Permissions", "03-app-security-app-permissions", "03 App Security", "feature"),
        ScreenSpec("Unknown Sources", "03-app-security-unknown-sources", "03 App Security", "feature"),
        ScreenSpec("Sideloaded Apps", "03-app-security-sideloaded-apps", "03 App Security", "feature"),
        ScreenSpec("App Activity", "03-app-security-app-activity", "03 App Security", "feature"),
        ScreenSpec("App Security Report", "03-app-security-app-security-report", "03 App Security", "feature"),
        ScreenSpec("Camera", "04-permission-and-privacy-camera", "04 Permission & Privacy", "feature"),
        ScreenSpec("Microphone", "04-permission-and-privacy-microphone", "04 Permission & Privacy", "feature"),
        ScreenSpec("Location", "04-permission-and-privacy-location", "04 Permission & Privacy", "feature"),
        ScreenSpec("Contacts", "04-permission-and-privacy-contacts", "04 Permission & Privacy", "feature"),
        ScreenSpec("SMS", "04-permission-and-privacy-sms", "04 Permission & Privacy", "feature"),
        ScreenSpec("Phone", "04-permission-and-privacy-phone", "04 Permission & Privacy", "feature"),
        ScreenSpec("Storage", "04-permission-and-privacy-storage", "04 Permission & Privacy", "feature"),
        ScreenSpec("Notifications", "04-permission-and-privacy-notifications", "04 Permission & Privacy", "feature"),
        ScreenSpec("Accessibility", "04-permission-and-privacy-accessibility", "04 Permission & Privacy", "feature"),
        ScreenSpec("Background Activity", "04-permission-and-privacy-background-activity", "04 Permission & Privacy", "feature"),
        ScreenSpec("Privacy Risk Score", "04-permission-and-privacy-privacy-risk-score", "04 Permission & Privacy", "feature"),
        ScreenSpec("Quick Scan", "05-malware-protection-quick-scan", "05 Malware Protection", "feature"),
        ScreenSpec("Full Device Scan", "05-malware-protection-full-device-scan", "05 Malware Protection", "feature"),
        ScreenSpec("File Scanner", "05-malware-protection-file-scanner", "05 Malware Protection", "feature"),
        ScreenSpec("App Scanner", "05-malware-protection-app-scanner", "05 Malware Protection", "feature"),
        ScreenSpec("Malware Detection", "05-malware-protection-malware-detection", "05 Malware Protection", "feature"),
        ScreenSpec("Suspicious File Detection", "05-malware-protection-suspicious-file-detection", "05 Malware Protection", "feature"),
        ScreenSpec("Quarantine", "05-malware-protection-quarantine", "05 Malware Protection", "feature"),
        ScreenSpec("Scan History", "05-malware-protection-scan-history", "05 Malware Protection", "feature"),
        ScreenSpec("Malware Reports", "05-malware-protection-malware-reports", "05 Malware Protection", "feature"),
        ScreenSpec("Wi-Fi Security", "06-network-security-wi-fi-security", "06 Network Security", "feature"),
        ScreenSpec("Current Network", "06-network-security-current-network", "06 Network Security", "feature"),
        ScreenSpec("Network Risk", "06-network-security-network-risk", "06 Network Security", "feature"),
        ScreenSpec("DNS Security", "06-network-security-dns-security", "06 Network Security", "feature"),
        ScreenSpec("Suspicious Connections", "06-network-security-suspicious-connections", "06 Network Security", "feature"),
        ScreenSpec("Unsafe Network Detection", "06-network-security-unsafe-network-detection", "06 Network Security", "feature"),
        ScreenSpec("Public Wi-Fi Warning", "06-network-security-public-wi-fi-warning", "06 Network Security", "feature"),
        ScreenSpec("VPN Status", "06-network-security-vpn-status", "06 Network Security", "feature"),
        ScreenSpec("Network History", "06-network-security-network-history", "06 Network Security", "feature"),
        ScreenSpec("URL Scanner", "07-web-protection-url-scanner", "07 Web Protection", "feature"),
        ScreenSpec("Website Risk Analyzer", "07-web-protection-website-risk-analyzer", "07 Web Protection", "feature"),
        ScreenSpec("Phishing Detection", "07-web-protection-phishing-detection", "07 Web Protection", "feature"),
        ScreenSpec("Malicious Website Detection", "07-web-protection-malicious-website-detection", "07 Web Protection", "feature"),
        ScreenSpec("Fake Website Detection", "07-web-protection-fake-website-detection", "07 Web Protection", "feature"),
        ScreenSpec("QR Code Scanner", "07-web-protection-qr-code-scanner", "07 Web Protection", "feature"),
        ScreenSpec("Safe Browsing", "07-web-protection-safe-browsing", "07 Web Protection", "feature"),
        ScreenSpec("Browser Protection", "07-web-protection-browser-protection", "07 Web Protection", "feature"),
        ScreenSpec("SMS Analysis", "08-phishing-and-scam-protection-sms-analysis", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Email Analysis", "08-phishing-and-scam-protection-email-analysis", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Message Analysis", "08-phishing-and-scam-protection-message-analysis", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("URL Analysis", "08-phishing-and-scam-protection-url-analysis", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("QR Analysis", "08-phishing-and-scam-protection-qr-analysis", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Scam Detection", "08-phishing-and-scam-protection-scam-detection", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Social Engineering Detection", "08-phishing-and-scam-protection-social-engineering-detection", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Scam Report", "08-phishing-and-scam-protection-scam-report", "08 Phishing & Scam Protection", "feature"),
        ScreenSpec("Account Inventory", "09-account-security-account-inventory", "09 Account Security", "feature"),
        ScreenSpec("Login Activity", "09-account-security-login-activity", "09 Account Security", "feature"),
        ScreenSpec("Suspicious Login Detection", "09-account-security-suspicious-login-detection", "09 Account Security", "feature"),
        ScreenSpec("Password Health", "09-account-security-password-health", "09 Account Security", "feature"),
        ScreenSpec("MFA Status", "09-account-security-mfa-status", "09 Account Security", "feature"),
        ScreenSpec("Breach Monitoring", "09-account-security-breach-monitoring", "09 Account Security", "feature"),
        ScreenSpec("Session Monitoring", "09-account-security-session-monitoring", "09 Account Security", "feature"),
        ScreenSpec("Account Risk", "09-account-security-account-risk", "09 Account Security", "feature"),
        ScreenSpec("Storage Analyzer", "10-file-and-storage-security-storage-analyzer", "10 File & Storage Security", "feature"),
        ScreenSpec("Suspicious Files", "10-file-and-storage-security-suspicious-files", "10 File & Storage Security", "feature"),
        ScreenSpec("Duplicate Files", "10-file-and-storage-security-duplicate-files", "10 File & Storage Security", "feature"),
        ScreenSpec("Dangerous Documents", "10-file-and-storage-security-dangerous-documents", "10 File & Storage Security", "feature"),
        ScreenSpec("Download Scanner", "10-file-and-storage-security-download-scanner", "10 File & Storage Security", "feature"),
        ScreenSpec("File Integrity", "10-file-and-storage-security-file-integrity", "10 File & Storage Security", "feature"),
        ScreenSpec("Secure Vault", "10-file-and-storage-security-secure-vault", "10 File & Storage Security", "feature"),
        ScreenSpec("Secure Delete", "10-file-and-storage-security-secure-delete", "10 File & Storage Security", "feature"),
        ScreenSpec("Behavioral Analysis", "11-ai-security-engine-behavioral-analysis", "11 AI Security Engine", "feature"),
        ScreenSpec("Anomaly Detection", "11-ai-security-engine-anomaly-detection", "11 AI Security Engine", "feature"),
        ScreenSpec("Threat Classification", "11-ai-security-engine-threat-classification", "11 AI Security Engine", "feature"),
        ScreenSpec("Risk Calculation", "11-ai-security-engine-risk-calculation", "11 AI Security Engine", "feature"),
        ScreenSpec("Threat Correlation", "11-ai-security-engine-threat-correlation", "11 AI Security Engine", "feature"),
        ScreenSpec("Security Recommendations", "11-ai-security-engine-security-recommendations", "11 AI Security Engine", "feature"),
        ScreenSpec("Continuous Risk Assessment", "11-ai-security-engine-continuous-risk-assessment", "11 AI Security Engine", "feature"),
        ScreenSpec("Ask Security Question", "12-ai-security-assistant-ask-security-question", "12 AI Security Assistant", "feature"),
        ScreenSpec("Explain Threat", "12-ai-security-assistant-explain-threat", "12 AI Security Assistant", "feature"),
        ScreenSpec("Analyze Screenshot", "12-ai-security-assistant-analyze-screenshot", "12 AI Security Assistant", "feature"),
        ScreenSpec("Analyze Message", "12-ai-security-assistant-analyze-message", "12 AI Security Assistant", "feature"),
        ScreenSpec("Analyze URL", "12-ai-security-assistant-analyze-url", "12 AI Security Assistant", "feature"),
        ScreenSpec("Explain App Permissions", "12-ai-security-assistant-explain-app-permissions", "12 AI Security Assistant", "feature"),
        ScreenSpec("Security Recommendations", "12-ai-security-assistant-security-recommendations", "12 AI Security Assistant", "feature"),
        ScreenSpec("Emergency Guidance", "12-ai-security-assistant-emergency-guidance", "12 AI Security Assistant", "feature"),
        ScreenSpec("Real-Time Protection", "13-security-monitor-real-time-protection", "13 Security Monitor", "feature"),
        ScreenSpec("Background Monitoring", "13-security-monitor-background-monitoring", "13 Security Monitor", "feature"),
        ScreenSpec("Threat Events", "13-security-monitor-threat-events", "13 Security Monitor", "feature"),
        ScreenSpec("Security Timeline", "13-security-monitor-security-timeline", "13 Security Monitor", "feature"),
        ScreenSpec("Recent Activities", "13-security-monitor-recent-activities", "13 Security Monitor", "feature"),
        ScreenSpec("Detection History", "13-security-monitor-detection-history", "13 Security Monitor", "feature"),
        ScreenSpec("Critical Alerts", "14-alert-center-critical-alerts", "14 Alert Center", "feature"),
        ScreenSpec("High Risk", "14-alert-center-high-risk", "14 Alert Center", "feature"),
        ScreenSpec("Medium Risk", "14-alert-center-medium-risk", "14 Alert Center", "feature"),
        ScreenSpec("Low Risk", "14-alert-center-low-risk", "14 Alert Center", "feature"),
        ScreenSpec("Alert Details", "14-alert-center-alert-details", "14 Alert Center", "feature"),
        ScreenSpec("Recommended Action", "14-alert-center-recommended-action", "14 Alert Center", "feature"),
        ScreenSpec("Alert History", "14-alert-center-alert-history", "14 Alert Center", "feature"),
        ScreenSpec("Device Check", "15-security-checkup-device-check", "15 Security Checkup", "feature"),
        ScreenSpec("App Check", "15-security-checkup-app-check", "15 Security Checkup", "feature"),
        ScreenSpec("Permission Check", "15-security-checkup-permission-check", "15 Security Checkup", "feature"),
        ScreenSpec("Network Check", "15-security-checkup-network-check", "15 Security Checkup", "feature"),
        ScreenSpec("Account Check", "15-security-checkup-account-check", "15 Security Checkup", "feature"),
        ScreenSpec("Privacy Check", "15-security-checkup-privacy-check", "15 Security Checkup", "feature"),
        ScreenSpec("Complete Security Report", "15-security-checkup-complete-security-report", "15 Security Checkup", "feature"),
        ScreenSpec("Report Threat", "16-incident-center-report-threat", "16 Incident Center", "feature"),
        ScreenSpec("Incident Details", "16-incident-center-incident-details", "16 Incident Center", "feature"),
        ScreenSpec("Evidence", "16-incident-center-evidence", "16 Incident Center", "feature"),
        ScreenSpec("Timeline", "16-incident-center-timeline", "16 Incident Center", "feature"),
        ScreenSpec("Threat Status", "16-incident-center-threat-status", "16 Incident Center", "feature"),
        ScreenSpec("Recommended Actions", "16-incident-center-recommended-actions", "16 Incident Center", "feature"),
        ScreenSpec("Incident History", "16-incident-center-incident-history", "16 Incident Center", "feature"),
        ScreenSpec("Lock Security Session", "17-emergency-protection-lock-security-session", "17 Emergency Protection", "feature"),
        ScreenSpec("Revoke Account Sessions", "17-emergency-protection-revoke-account-sessions", "17 Emergency Protection", "feature"),
        ScreenSpec("Mark Device Compromised", "17-emergency-protection-mark-device-compromised", "17 Emergency Protection", "feature"),
        ScreenSpec("Disable Trusted Access", "17-emergency-protection-disable-trusted-access", "17 Emergency Protection", "feature"),
        ScreenSpec("Emergency Scan", "17-emergency-protection-emergency-scan", "17 Emergency Protection", "feature"),
        ScreenSpec("Security Contact", "17-emergency-protection-security-contact", "17 Emergency Protection", "feature"),
        ScreenSpec("Daily Security Summary", "18-security-reports-daily-security-summary", "18 Security Reports", "feature"),
        ScreenSpec("Weekly Security Summary", "18-security-reports-weekly-security-summary", "18 Security Reports", "feature"),
        ScreenSpec("Threat Report", "18-security-reports-threat-report", "18 Security Reports", "feature"),
        ScreenSpec("Privacy Report", "18-security-reports-privacy-report", "18 Security Reports", "feature"),
        ScreenSpec("Network Report", "18-security-reports-network-report", "18 Security Reports", "feature"),
        ScreenSpec("App Risk Report", "18-security-reports-app-risk-report", "18 Security Reports", "feature"),
        ScreenSpec("Device Security Report", "18-security-reports-device-security-report", "18 Security Reports", "feature"),
        ScreenSpec("Profile", "19-settings-profile", "19 Settings", "feature"),
        ScreenSpec("Scan Settings", "19-settings-scan-settings", "19 Settings", "feature"),
        ScreenSpec("About", "19-settings-about", "19 Settings", "feature")
    )

    val byRoute: Map<String, ScreenSpec> = all.associateBy { it.route }
    val byGroup: Map<String, List<ScreenSpec>> = all.groupBy { it.group }

    fun find(route: String): ScreenSpec = byRoute[route] ?: all.first()
}